### ISSUE TITLE
Is '@mertefecerit/vuetable/Datatable.vue' the correct form to import it?

### ISSUE THREAD

**Issue by ohmmolina** [mertefecerit/client-side-vue-datatable#4]
After the npm install, what else I have to do to use it in my vue app?
I try to import in the next way:
```import Datatable from '@mertefecerit/vuetable'```
But I notice the package doesn't have any index.js. Then, I imported it as 
```import Datatable from '@mertefecerit/vuetable/Datatable.vue'```
and it worked. But isn't better to import it automatically with '@mertefecerit/vuetable' ?

**Comment by mertefecerit** [comment]
When I initially created this package, I wasn't experienced enough, and it could handle it without the .vue extension on webpack. Later, I switched to Vite, and the need to include the .vue extension arose. Due to the workload, I'm unable to make more user-friendly improvements. I apologize for any inconvenience caused by this unfortunate experience.
